version: '3.8'
services:

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://172.31.41.7:8000
    ports:
      - "5173:80"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:80"
    depends_on:
      - postgres
    environment:
      - BACKEND_CORS_ORIGINS="http://localhost,http://localhost:5173,https://localhost,https://localhost:5173,http://13.51.205.103:5173,http://13.51.205.103,http://shirlynewanjiru.chickenkiller.com"
      - SECRET_KEY=changethis123
      - PROJECT_NAME=Full Stack FastAPI Project
      - FIRST_SUPERUSER=devops@hng.tech
      - FIRST_SUPERUSER_PASSWORD=Devops@hng
      - USERS_OPEN_REGISTRATION=True
      - POSTGRES_SERVER=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_DB=db
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password

  postgres:
    image: 'postgres:15'
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: username
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db

  proxy:
    image: 'jc21/nginx-proxy-manager:latest'
    restart: unless-stopped
    ports:
      - '8090:81'
    volumes:
      - ./proxy/data:/data
      - ./proxy/letsencrypt:/etc/letsencrypt

  adminer:
    image: adminer:latest
    restart: always
    ports:
      - "8080:8080"
    environment:
      ADMINER_DEFAULT_SERVER: postgres

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./proxy_params.conf:/etc/nginx/proxy_params.conf
      - ./nginx/letsencrypt:/etc/letsencrypt
    ports:
      - "80:80"
    depends_on:
      - frontend
      - backend
      - postgres
      - adminer 
      - proxy
